logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/my-app/record.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: asctime
      time_format: "%Y-%m-%d %H:%M:%S,%f"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.levelname
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, move_severity]



