name: Integration Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up PostgreSQL
      run: |
        sudo systemctl enable postgresql
        sudo systemctl start postgresql
        sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USER }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
        sudo -u postgres psql -c "ALTER USER ${{ secrets.DB_USER }} WITH SUPERUSER;"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r flask-app/requirements.txt


    - name: Run integration tests
      run: |
        mkdir /var/log/my-app/
        cd flask-app
        python3 -m pytest -p no:warnings
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: postgres
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}